export {Hero} from './Hero/Hero'
export { GetStarted} from './GetStarted/GetStarted'
export {Reviews} from './Reviews/Reviews'
export { Features} from './Features/Features'
export {Footer} from './Footer/Footer'